apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: k8s-in-a-shell
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/sarveshraj/k8s-in-a-shell/frontend:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
