apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: learnk8s
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
