apiVersion: batch/v1
kind: CronJob
metadata:
  name: worker-cronjob
  namespace: learnk8s
  labels:
    app: worker
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: worker
              image: ghcr.io/sarveshraj/learnk8s/worker:0.1
              imagePullPolicy: Always
          restartPolicy: OnFailure
