apiVersion: batch/v1
kind: CronJob
metadata:
  name: worker-cronjob
  namespace: k8s-in-a-shell
  labels:
    app: worker
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: worker
              image: ghcr.io/sarveshraj/k8s-in-a-shell/worker:0.1
              imagePullPolicy: Always
          restartPolicy: OnFailure
