apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: learnk8s
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-data
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: false
