apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: k8s-in-a-shell
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ghcr.io/sarveshraj/k8s-in-a-shell/server:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
