apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  namespace: k8s-in-a-shell
  labels:
    app: server
spec:
  containers:
    - name: server
      image: ghcr.io/sarveshraj/k8s-in-a-shell/server:0.1
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
