apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  namespace: learnk8s
  labels:
    app: server
spec:
  containers:
    - name: server
      image: ghcr.io/sarveshraj/learnk8s/server:0.1
      ports:
        - containerPort: 8080
